### ISSUE TITLE
Change license in installers & docs

### ISSUE THREAD

**Issue by ugurdogrusoz** [PathwayCommons/chibe#66]
The license should be LGPL.

**Comment by ozgunbabur** [comment]
The reason for EPL is the Eclipse libraries that Chisio uses. Can we build an LGPL tool using EPL components?

**Comment by ugurdogrusoz** [comment]
Looks like EPL is a more relaxed license anyway. Let's just keep it.
https://resources.whitesourcesoftware.com/blog-whitesource/top-10-eclipse-public-license-questions-answered
