### ISSUE TITLE
Compound node members could be sorted alphabetically

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayCommons/chibe#69]
ChiBE tiles the members of a Complex in mechanistic view, similarly when rendering a SIF network, ChiBE groups the nodes with the same topology, which helps for complexity management. However, when the compound node has too many members, it becomes difficult to find a member because they are not sorted alphabetically.

The current design of the tiling algorithm does not allow for sorting members because the tiling is not performed first left-to-right then up-to-bottom. Current algorithm always try to maintain a square while the compound grows with new members, hence it grows from topleft-to-bottomright. We may consider changing this design to favor member sorting.

**Comment by ozgunbabur** [comment]
The relevant part of the code to change this is below.

https://github.com/PathwayCommons/chibe/blob/master/src/main/java/org/gvt/layout/BiPaLayout.java#L173

**Comment by ozgunbabur** [comment]
There is some bug in the implementation. Try loading below sif (remove the .txt extension, github does not let me load .sif directly).

[CREB1-neighborhood.sif.txt](https://github.com/PathwayCommons/chibe/files/1607436/CREB1-neighborhood.sif.txt)

You will see that compound members are mostly ordered alphabetically. Mostly! Look at the end of them.

**Comment by metincansiper** [comment]
@ozgunbabur ```getWith()``` in https://github.com/PathwayCommons/chibe/blob/master/src/main/java/org/gvt/layout/BiPaLayout.java#L287 is calling ```shiftToLastRow()```. It seems that this call is the reason of the bug. Shall I remove that call and the method itself as well if it has no other usage?

**Comment by ozgunbabur** [comment]
Yes, I don't see any reason a getter method should modify the organization.
Please try removing it.

**Comment by metincansiper** [comment]
I removed it in PR #71
